#!/bin/bash

#array modules, put here the modules you nedd compile and replace.
modules_array[0]=c-e-o-core



abort()
{
  echo >&2 '
  *************************************************************
  *** erro - operacao abortada - script compile_and_replace ***
  *************************************************************
  '

  echo "An error occurred. Exiting..." >&2
  exit 1
}



trap 'abort' INT

for i in "${modules_array[@]}"
do
   :  
   case ${i} in
	module_x)
		./modules/compile_and_replace_c_e_webservices_provider $1
		;;
	module_y)
		./modules/compile_and_replace_c_e_feasibility_qualification $1
		;;
	*)
		echo "componente invalido"
		;;
  esac
done
