#!/bin/bash

#functions

define(){
	# versao instalada
	export VERSION=version
	# versao do pom (se o amb estiver desatualizado essa versao difere da versao instalada) 
	export POM_VERSION=version
	export SERVER_BIN=~/desenv/server/wildfly-8.2.0.Final/bin
	export DEPLOYMENTS=~/desenv/server/wildfly-8.2.0.Final/ports-$1/deployments
	export INTEGRATION_LIB=${DEPLOYMENTS}/x-y-w-ear-$VERSION.ear/lib
	export WEBDESKMAPREPORT_LIB=${DEPLOYMENTS}/x-y-k-ear-$VERSION.ear/lib/lib
	export BIN_DIR=~/bin
}

compile_and_replace_modules(){
	if [ "-c" == $1 ]; then
		echo chamando script de compilacao;
		compile_and_replace $2;
		echo fim script de compilacao;
	fi
}

clean(){
cd $DEPLOYMENTS
rm -rf *.deployed *.failed *.dodeploy *.isdeploying *.undeployed
}

create_dodeploy(){
#touch x-y-k-ear-$VERSION.ear/lib.dodeploy
}

up(){
$SERVER_BIN/debugports-$1.sh
}


#begin
port=$1
compile_flag=$2
replace_flag=$3

define $port

cd $BIN_DIR

compile_and_replace_modules $compile_flag $replace_flag

clean

create_dodeploy

up $1





